<?php

namespace App\CommonModule\Presenters;

use Nette;


class UserPresenter extends BasePresenter
{
    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        if(!$this->user->isLoggedIn()) {
            $this->redirect(':Common:Home:default');
        }
    }

    public function actionDefault()
    {
        $this->template->userIdentity = $this->user->getIdentity();
    }

}
