<?php

namespace App\ModeratorModule\Presenters;

use App\Components\Form\ArticleForm;
use App\Model\Service\Article;
use Cepi\StringUtils;
use Nette;


class ArticlePresenter extends BasePresenter
{
    public $article;

    /** @var Article $articleService */
    public $articleService;

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub

        $this->articleService = $this->context->getService('Article');
    }
    public function actionAdd()
    {

    }

    public function createComponentAddArticleForm()
    {
        $form = new ArticleForm();
        $form->addSubmit('submit', 'Uložit');

        $form->onSuccess[] = [$this, 'addArticleFormSuccess'];
        return $form;
    }

    public function addArticleFormSuccess(Nette\Forms\Form $form)
    {
        $values = $form->getValues();
        $this->articleService->insert([
            'headline' => StringUtils::tmws($values->headline),
            'content' => $values->content,
            'state' => $values->publish ? 'published' : 'waiting',
            'user_id' => $this->getUser()->id,
            'created' => (new \DateTime())->format('Y-m-d')
        ]);

        $this->flashMessage('Článek přidán', 'success');
        $this->redirect(':Common:Article:list');
    }
}
