<?php

namespace App\AdminModule\Presenters;


use App\Components\Form\VaccinationForm;
use App\Model\Service\Vaccination;
use Cepi\StringUtils;
use Nette;


class VaccinationPresenter extends BasePresenter
{
    public $vac;

    /** @var Vaccination $vacService */
    public $vacService;

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub

        $this->vacService = $this->context->getService('Vaccination');
    }

    public function actionDefault($id)
    {
        $vac = $this->vacService->getById($id);
        if($vac !== false) {
            $this->vac = $vac;
            $this->template->vac = $this->vac;
            $this->template->cats = $this->vacService->getCats($vac);
        } else {
            throw new Nette\Application\BadRequestException('Vaccination does not exist', 404);
        }
    }

    public function actionList()
    {
        $this->template->vaccinations = $this->vacService->getAll();
    }


    public function actionAdd()
    {

    }

    public function createComponentAddVaccinationForm()
    {
        $form = new VaccinationForm();

        $form->addSubmit('submit', 'Přidat');

        $form->onSuccess[] = array($this, 'addVaccinationFormSuccess');

        return $form;
    }

    public function addVaccinationFormSuccess(Nette\Forms\Form $form)
    {
        $values = $form->getValues();

        $this->vacService->insert([
            'name' => StringUtils::tmws($values->name),
            'severity' => StringUtils::caws($values->severity)
        ]);

        $this->flashMessage('Očkování bylo přidáno', 'info');
        $this->redirect('list');
    }

    public function actionEdit($id)
    {
        $vac = $this->vacService->getById($id);
        if($vac !== false) {
            $this->vac = $vac;
        } else {
            throw new Nette\Application\BadRequestException('Vaccination does not exist', 404);
        }
    }

    public function createComponentEditVaccinationForm()
    {
        $form = new VaccinationForm();

        $form->setDefaults([
            'name' => $this->vac->name,
            'severity' => $this->vac->severity
        ]);

        $form->addSubmit('submit', 'Uložit');

        $form->onSuccess[] = array($this, 'editVaccinationFormSuccess');

        return $form;
    }

    public function editVaccinationFormSuccess(Nette\Forms\Form $form)
    {
        $values = $form->getValues();
        if($this->vac) {
            $this->vac->update([
                'name' => StringUtils::tmws($values->name),
                'severity' => StringUtils::caws($values->severity)
            ]);
            $this->flashMessage('Očkování bylo upraveno', 'info');
        } else {
            $this->flashMessage('Očkování neexistuje', 'warning');
        }

        $this->redirect('list');
    }

}

